-- StockPilot cloud setup — run this ONCE in your Supabase project.
-- Supabase dashboard → SQL Editor → New query → paste this whole file → Run.

-- Stores: each row is one physical shop belonging to one login.
create table if not exists public.stores (
  id         text primary key,                -- generated by the app
  user_id    uuid not null references auth.users(id) on delete cascade,
  name       text not null,
  currency   text not null default 'INR',
  created_at timestamptz not null default now()
);

-- Inventory items, one per store.
create table if not exists public.items (
  id          text primary key,               -- generated by the app (same id as local)
  user_id     uuid not null references auth.users(id) on delete cascade,
  store_id    text not null references public.stores(id) on delete cascade,
  name        text not null,
  description text,
  category    text,
  qty         integer not null default 0,
  price       numeric not null default 0,
  cost        numeric not null default 0,
  threshold   integer not null default 5,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Sales / store-use log.
create table if not exists public.sales (
  id      text primary key,                   -- generated by the app (same id as local)
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null references public.stores(id) on delete cascade,
  item_id text not null,
  name    text not null,
  qty     integer not null,
  price   numeric not null default 0,
  kind    text not null default 'sale',       -- 'sale' | 'use'
  ts      timestamptz not null default now(),
  date    date                                -- local calendar day (YYYY-MM-DD), used by daily/weekly reports
);

create index if not exists items_store_idx   on public.items(store_id);
create index if not exists sales_store_idx   on public.sales(store_id);
create index if not exists sales_ts_idx      on public.sales(ts);

-- For projects set up before these columns existed (safe to re-run):
alter table public.sales add column if not exists date date;
alter table public.sales add column if not exists custom boolean not null default false; -- per-sale custom price (chat "custom sale")
alter table public.items add column if not exists cost numeric not null default 0;

-- Row Level Security: a signed-in user can only ever touch their own rows.
alter table public.stores enable row level security;
alter table public.items  enable row level security;
alter table public.sales  enable row level security;

create policy "own stores" on public.stores
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own items" on public.items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own sales" on public.sales
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Assistant conversation, one row per store (so it follows the user across devices).
create table if not exists public.chats (
  id         text primary key,                -- same id as the store it belongs to
  user_id    uuid not null references auth.users(id) on delete cascade,
  store_id   text not null references public.stores(id) on delete cascade,
  messages   jsonb not null default '[]',
  updated_at timestamptz not null default now()
);
alter table public.chats enable row level security;
create policy "own chats" on public.chats
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
